In [2]:
import numpy as np
import time

In [3]:
# Execution performace
size = 1_000_000

# Python List
py_list = list(range(size))
start = time.time()
sq = [x ** 2 for x in py_list]
end = time.time()
print(f"Python list time = {end - start} seconds")

# Numpy Array
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"Python list time = {end - start} seconds")

Python list time = 0.1394798755645752 seconds
Python list time = 0.003191709518432617 seconds


In [4]:
import sys

print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy Array size = {np_arr.nbytes} bytes")

Python list size = 8000056000000 bytes
Numpy Array size = 8000000 bytes


In [12]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D, type(arr2D), arr2D.dtype, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'> <U21 (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [22]:
# Create numpy array from scratch
arr1 = np.zeros((2, 3), dtype="int64") #Prefill with zeros
print(arr1, arr1.shape)

arr2 = np.ones((3, 3), dtype="int64") #Prefill with ones
print(arr2, arr2.shape)

arr3 = np.full((3, 3), 100) #Prefill with value
print(arr3, arr3.dtype)

arr4 = np.eye(3) #Identity Matrix
print(arr4, arr4.shape)

arr5 = np.arange(1, 10) #Range Elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) #Evenly space arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]] (3, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]] int64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 2 3 4 5 6 7 8 9] (9,)
[  1.  34.  67. 100.] (4,)


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape) # Dimension m * n
print(arr.size) # Total elements : 9
print(arr.dtype) # Data Type: int64
print(arr.ndim) # Number of 

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [35]:
# Operations on Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.dtype)

reShaped = arr.reshape((3, 2)) #Reshape --> row into column --> column into row
print(reShaped, arr.dtype)

flattened = arr.flatten() #2D => 1D
print(flattened, flattened.dtype)


[[1 2 3]
 [4 5 6]] int64
[[1 2]
 [3 4]
 [5 6]] int64
[1 2 3 4 5 6] int64


In [39]:
# Indexing
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1[1]) # 2
print(arr1[3]) # 4

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[0][1])
print(arr2[1][1])

2
4
2
5


In [40]:
# Fancy Indexing
arr = np.array([1, 2, 3, 4, 5])
index = [0, 1, 4]
print(arr[index])

[1 2 5]


In [43]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 3]) 
print(arr[arr % 2 == 0]) # Even Numbers 
print(arr[arr % 2 != 0]) # Odd Numbers 

[4 5]
[2 4]
[1 3 5]


In [49]:
# Sliding Operation

arr = np.array([1, 2, 3, 4, 5])

# [start, end, step]

print(arr[1: 4]) # [2, 3, 4]
print(arr[1: ])
print(arr[: 4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [52]:
# Copy vs View

#Copy
arr1 = [10, 20, 30, 40, 50]
sub_list = arr1[1 : 4]
print(sub_list)
sub_list[1] = 200

print(sub_list)
print(arr1)

#View
arr2 = np.array([1, 2, 3, 4, 5])
sub_arr2 = arr2[1: 4]
print(sub_arr2)
sub_arr2[1] = 200

print(sub_arr2)
print(arr2)

#.copy()
arr3 = np.array([1, 2, 3, 4, 5])
sub_arr3 = arr2[1: 4].copy()
print(sub_arr3)
sub_arr2[1] = 200

print(sub_arr3)
print(arr3)


[20, 30, 40]
[20, 200, 40]
[10, 20, 30, 40, 50]
[2 3 4]
[  2 200   4]
[  1   2 200   4   5]
[  2 200   4]
[  2 200   4]
[1 2 3 4 5]


In [59]:
# Data Types

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1, arr1.dtype) #int64

arr2 = np.array([1, 2, 3.14, 4, 5])
print(arr2, arr2.dtype) #float64

arr3 = np.array([1, 2, "Hello", 4, 5])
print(arr3, arr3.dtype) #<U21

arr4 = np.array([1, 2, True, 4, 5])
print(arr4, arr4.dtype) #<U21

arr5 = np.array([2 + 3j])
print(arr5, arr5.dtype) #complex128

arr6 = np.array(["Prime", 1, 2, {"one": 1, "two": 2}, 3.14])
print(arr6, arr6.dtype)

[1 2 3 4 5] int64
[1.   2.   3.14 4.   5.  ] float64
['1' '2' 'Hello' '4' '5'] <U21
[1 2 1 4 5] int64
[2.+3.j] complex128
['Prime' 1 2 {'one': 1, 'two': 2} 3.14] object


In [ ]:
# Multi-Dimensional Array
arr2D = np.array([[1, 2, 3,], [4, 5, 6], [6, 7, 8]])
print(arr2D)
print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns) #Sum of columns

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows) #Sum of rows

print(arr2D[0:2, 0: 1]) #Particular Elements

[[1 2 3]
 [4 5 6]
 [6 7 8]]
42
[11 14 17]
[ 6 15 21]
[[1]
 [4]]


In [79]:
#3D array
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(arr3D)

#Indexing
print(arr3D[0][1][1])
print(arr3D[1][1][0])

#Slicing
print(arr3D[:, 0, :]) #First row from both layers
print(arr3D[:, :, 0]) #First column from both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [80]:
# Vectorization

arr = np.array([1, 2, 3, 4, 5])

print(arr ** 2) # Print Squares of each elements
print(arr + 10) # Add 10 in each elements

[ 1  4  9 16 25]
[11 12 13 14 15]


In [84]:
# Braodcasting
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print (arr1 + arr2)


# We can't broadcasting for it
# arr3 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
# arr4 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
# print(arr3 + arr4) 

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [88]:
#Normalized Array

arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

print(mean)
print(std_dev)


normalize_arr = (arr-mean) / std_dev
print(normalize_arr)


2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
